id: P005550
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG9604
  title: འདུལ་བ་མེ་ཏོག་ཕྲེང་རྒྱུད་ཀྱི་ཊཱི་ཀ་སོགས་འགྲེལ་པ་དཀོན་རིགས་ཁག་ཅིག
  author: ''
  volumes:
    70bfa299510a4597bf990604f30ec424:
      image_group_id: I1KG9627
      title: ''
      volume_number: 1
      total_pages: 456
      base_file: v001.txt
