id: P005550
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 11:58:49.434240
source_metadata:
  id: bdr:W1KG9604
  title: འདུལ་བ་མེ་ཏོག་ཕྲེང་རྒྱུད་ཀྱི་ཊཱི་ཀ་སོགས་འགྲེལ་པ་དཀོན་རིགས་ཁག་ཅིག
  author: ''
  volumes:
    70bfa299510a4597bf990604f30ec424:
      image_group_id: I1KG9627
      title: ''
      volume_number: 1
      total_pages: 456
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
